/* SEGUNDO CAPITULO */
	/*
	DECLARANDO VARIAVEIS 
( DECLARE- DECLARANDO VARIAVEL - @NOME - TODA VARIAVEL EM T-SQL PRECISA DE @ NO INICIO E SEU TIPO VARCHAR,CHAR,INT,DECIMAL,NUMERIC,BIT )
	VOCE PODE COLOCAR VALOR DE TRÊS MANEIRAS COMO VOU DEMONSTRAR ABAIXO.*/
	

/*
DECLARE @IDADE	INT
DECLARE @NOME	VARCHAR(200)
DECLARE	@DATA	DATE


DECLARE @IDADE2 INT, @NOME2		VARCHAR(200), @DATA2 DATE
	
	--SET @IDADE = 20
	--PRINT 'a SUA IDADE É: '+ CONVERT(CHAR(3), @IDADE)
	--SET @NOME = 'JOÃO DA SILVA'
	--PRINT 'SEU NOME E : '+ @NOME
	--SET @DATA ='20180501'
	--PRINT @DATA


DECLARE @CPF VARCHAR(12)
	SET @CPF ='1471156710'

--SELECT NOME,[DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES]
--WHERE CPF=@CPF

SELECT @NOME2=NOME,@DATA2=[DATA DE NASCIMENTO],@IDADE2=IDADE FROM [TABELA DE CLIENTES]
WHERE CPF=@CPF
	PRINT 'NOME :'+@NOME2 +'  ANO NASCIMENTO : '+ CONVERT(CHAR(8),@DATA2,112)+' IDADE :'+ CAST(@IDADE2 AS CHAR(3))
*/

DECLARE @MATRICULA VARCHAR(5), @NOME	VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(100)

	SET @MATRICULA='00240'
	SET @NOME	='ANA CLAUDIA'
	SET @PERCENTUAL	=0.15
	SET @DATA = '20131201'
	SET @FERIAS =1
	SET	@BAIRRO = 'JD LUCELIA - GRAJAÚ'

	INSERT INTO [TABELA DE VENDEDORES](MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
	VALUES
	(@MATRICULA,@NOME,@PERCENTUAL,@DATA,@FERIAS,@BAIRRO)


SELECT * FROM [TABELA DE VENDEDORES] WHERE MATRICULA=@MATRICULA
	