/* PRIMEIRA AULA DE T-SQL */


/*
	O QUE É T-SQL ?
			JA UTILIZAMOS T-SQL A MUITO TEMPO POIS SELECT,INSERT,DELETE,CREATE, DROP,UPDATE ...
			T-SQL, O T E DE TRANSACTION ... PORÉM O T-SQL PODE SER USANDO COMO MODULO DE PROGRAMÇÃO...
			O T-SQL E UMA LINGUAGEM PROPRIETÁRIA DA MICROSOFT....			

	EXEMPLIFIQUE UM COMANDO DE T-SQL
	
		UPDATE - ATUALIZAÇÃO DE VALOR SE ENCAIXA EM T-SQL...
			
*/